# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be95a20fac1cabe88f9f681c440590423f17cc72d088ffac89bf800d6ec59c414ca00fbe7287de66ffda0f2c472e74985d7e61ac5ad7b0c6f158a241fb944682

test:
  secret_key_base: 0dcca9b07df6cde8edf9eebbbdbfe17f50c643474424790367916516cdbc306426617e81fc0aa767780a7a6951acec33b5229a3081f1733d94746fee34480e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
